name: Build, test and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Set up Node.js version 20
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 4: Install dependencies with Yarn
      - name: Install dependencies
        run: yarn install
        working-directory: ./webapp

      # Step 5: Run linter
      - name: Run linter
        run: yarn lint
        working-directory: ./webapp

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./webapp   # Set context to webapp directory
          file: ./webapp/Dockerfile   # Dockerfile is inside webapp directory
          push: true   # Push image to Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
