name: Build and test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stap om de repository code te check out-en
      - name: Checkout code
        uses: actions/checkout@v3
